### ISSUE TITLE
Lack of documentation for -setDateHasItemsCallback:

### ISSUE THREAD

**Issue by Abhijay** [hons82/THCalendarDatePicker#19]
Hey, I was hoping you could provide more documentation as to what this part of your initialization does:

[self.datePicker setDateHasItemsCallback:^BOOL(NSDate *date) {
        int tmp = (arc4random() % 30)+1;
        if(tmp % 5 == 0)
            return YES;
        return NO;
    }];

**Comment by hons82** [comment]
If you start the example you'll notice that there are little dots under some dates. Those dates are randomly chosen by the code you question.

You could use them like the native iOS calendar does to show which dates have detail items and which not. Obviously you'd need to remove the random part and take the real dates from a datasource like coredata.
