### ISSUE TITLE
delegate method for when closing by touching outside calendar?

### ISSUE THREAD

**Issue by cdbeshore** [hons82/THCalendarDatePicker#22]
Hi. I can't find a way to track when a user brings up the calendar, then dismisses by touching outside the calendar. It doesn't call datePickerCancelPressed. Maybe I'm missing something. Any help is appreciated.

Love this simple calendar control. Fits my app well.

**Comment by hons82** [comment]
Hi,
actually you're supposed to close the picker by yourself when `datePickerCancelPressed` is called, so it can't call that specific method.
If you'd check the code of `KNSemiModalViewController` which I used to create the semitransparent background, you'd see these 3 notifications

```objective-c
#define kSemiModalDidShowNotification @"kSemiModalDidShowNotification"
#define kSemiModalDidHideNotification @"kSemiModalDidHideNotification"
#define kSemiModalWasResizedNotification @"kSemiModalWasResizedNotification"
```

I can understand that you don't wanna catch the notification so I added an optional method in the protocol that will be called when the date picker has been hidden.

```objective-c
@protocol THDatePickerDelegate <NSObject>

-(void)datePickerDonePressed:(THDatePickerViewController *)datePicker;
-(void)datePickerCancelPressed:(THDatePickerViewController *)datePicker;

@optional

-(void)datePicker:(THDatePickerViewController *)datePicker selectedDate:(NSDate *)selectedDate;
-(void)datePickerDidHide:(THDatePickerViewController *)datePicker;

@end
```

**Comment by cdbeshore** [comment]
awesome. Thanks for adding this. I always try to think of all they ways that a user would cancel the modal and catch them to update the UI. Thanks for this date picker.
