### ISSUE TITLE
startDate and stopDate range

### ISSUE THREAD

**Issue by gitabdelkarim** [hons82/THCalendarDatePicker#24]
I'm developing an app in which the user is supposed to select a future date. It would be really nice if there was a property (e.g. NSDate *startdate) on the calendar that made sure no dates earlier than that are displayed, and a property (e.g. NSDate *stopdate) that made sure no dates after that are displayed.

**Comment by hons82** [comment]
Hi, 
actually you can set a property that allows the selection of future dates only

```objective-c
    [self.datePicker setDisableHistorySelection:YES];
    [self.datePicker setDisableFutureSelection:NO];
```
