### ISSUE TITLE
Come to today by a single click?

### ISSUE THREAD

**Issue by antonyjoemathew** [hons82/THCalendarDatePicker#25]
In my app I am using this calendar.I want 2 functionality’s
1.After going to some other month by clicking next/previous button,is there any way to come back to the current month view by a single click
2.I am adding some events dynamically in the calendar,how should I add dots at the same time of adding event for a particular date.

**Comment by hons82** [comment]
1) There is the possibility to have a `TODAY` button on the top center of the control which brings you back to today.
```objective-c
    [self.datePicker setAllowClearDate:NO];
    [self.datePicker setClearAsToday:YES];
```
2) That's the piece of code you'll need to set the dots
```objective-c
[self.datePicker setDateHasItemsCallback:^BOOL(NSDate *date) {
     int tmp = (arc4random() % 30)+1;
     if(tmp % 5 == 0)
     return YES;
     return NO;
     }];
```
In this case it is putting random dots, but if you compare the date in the parameter with the dates you want the dots you can set them to it.

**Comment by antonyjoemathew** [comment]
Thank you for your reply.
In the case 2,I am able to put the dots while loading the calendar.What I want is,After selecting a date by clicking it, I will add some event to that date like the iOS default calendar.After adding that event I want to show the dot in that particular date

**Comment by hons82** [comment]
Hmmm... Currently there is no way to do that without completely repainting it.
###Possible solution
The only cell that you keep a reference in the controller is the currently selected day, so it would be easy to set/unset the `hasItemsIndicator` boolean of that particular cell and repaint only that.

**Comment by antonyjoemathew** [comment]
Thank you :+1:
