### ISSUE TITLE
When use it by cocoapods in swift project，the app can not load image

### ISSUE THREAD

**Issue by sparkdreamstudio** [hons82/THCalendarDatePicker#27]

**Comment by hons82** [comment]
I didn't use it in a Swift project so far, but I've seen that there are some errors in cocoapods and xcassets.
[issue](https://github.com/CocoaPods/CocoaPods/issues/1549)
Do u c the images in xcode?

However, I need to c it in an example to confirm it and find a solution

**Comment by sparkdreamstudio** [comment]
![e2152247-e3b5-41fd-b4c8-00c28d5add2d](https://cloud.githubusercontent.com/assets/1477665/7826982/319b815e-0454-11e5-80e1-e83c71283b91.png)
![ios simulator screen shot 2015 5 27 9 36 32](https://cloud.githubusercontent.com/assets/1477665/7826986/3924325e-0454-11e5-816d-3d56a23b6d71.png)
i take the pic of xcode debug  cmd and simulator img, is it OK ?

**Comment by hons82** [comment]
I've added a sample project that currently works in Swift.
Actually there have been quite some changes, that I haven't been aware of.
Thx 4 helping, I'll mention u in the contributions list

**Comment by sparkdreamstudio** [comment]
thk u :-)

**Comment by Alexey-Khlebnikov** [comment]
I used 1.3.0 instead of 1.2.9 like this:
pod 'THCalendarDatePicker', '~> 1.3.0'
it works well
