### ISSUE TITLE
iOS7 crash because of iOS8 api

### ISSUE THREAD

**Issue by czzhengkw** [hons82/THCalendarDatePicker#29]
In THDateDay.m line 35,40
In THDatePickerViewController.m line 122,466
+ (UIImage *)imageNamed:(NSString *)name inBundle:(NSBundle *)bundle compatibleWithTraitCollection:(UITraitCollection *)traitCollection NS_AVAILABLE_IOS(8_0);

**Comment by hons82** [comment]
I just commited a version (not yet to cocoapods)
This error was introduced due to #27 and I didn't test it since then on iOS7

**Comment by czzhengkw** [comment]
Could you commit to cocoapods, I always have some thing wrong...


duplicate symbol _KNSemiModalTransitionStyle in:
    /Users/Keven/Library/Developer/Xcode/DerivedData/Pet-iOS-ewdourhacbgcgdevppgxdsuspkxi/Build/Intermediates/Pet-iOS.build/Debug-iphonesimulator/Pet-iOS.build/Objects-normal/x86_64/StoreDetailViewController.o
    /Users/Keven/Library/Developer/Xcode/DerivedData/Pet-iOS-ewdourhacbgcgdevppgxdsuspkxi/Build/Intermediates/Pet-iOS.build/Debug-iphonesimulator/Pet-iOS.build/Objects-normal/x86_64/THDatePickerViewController.o
duplicate symbol _KNSemiModalTransitionStyle in:
    /Users/Keven/Library/Developer/Xcode/DerivedData/Pet-iOS-ewdourhacbgcgdevppgxdsuspkxi/Build/Intermediates/Pet-iOS.build/Debug-iphonesimulator/Pet-iOS.build/Objects-normal/x86_64/StoreDetailViewController.o
    /Users/Keven/Library/Developer/Xcode/DerivedData/Pet-iOS-ewdourhacbgcgdevppgxdsuspkxi/Build/Intermediates/Pet-iOS.build/Debug-iphonesimulator/Pet-iOS.build/Objects-normal/x86_64/OrderConfirmViewController.o
duplicate symbol _KNSemiModalTransitionStyle in:
    /Users/Keven/Library/Developer/Xcode/DerivedData/Pet-iOS-ewdourhacbgcgdevppgxdsuspkxi/Build/Intermediates/Pet-iOS.build/Debug-iphonesimulator/Pet-iOS.build/Objects-normal/x86_64/StoreDetailViewController.o
    /Users/Keven/Library/Developer/Xcode/DerivedData/Pet-iOS-ewdourhacbgcgdevppgxdsuspkxi/Build/Intermediates/Pet-iOS.build/Debug-iphonesimulator/Pet-iOS.build/Objects-normal/x86_64/UIViewController+KNSemiModal.o
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hons82** [comment]
The files are present twice, but never mind.
I hope I'll get to it tomorrow.

btw
If you want to test the latest version of a Pod (so the current state of the git) just use
```
pod 'THCalendarDatePicker', :git => 'https://github.com/hons82/THCalendarDatePicker.git'
```
[There are a lot of possibilites when you define the podfile](https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo)

**Comment by czzhengkw** [comment]
OK,thank you...

**Comment by hons82** [comment]
Okay... I just tried it and it seemed to work on iOS7 again
Just made the push to cocoapods, v1.1.1 so it should work soon
