### ISSUE TITLE
Calendar dates are localised

### ISSUE THREAD

**Issue by varkor** [hons82/THCalendarDatePicker#30]
Though this might be desirable in some scenarios, having each day set relative to the user's timezone, rather than relative to UTC, means that it is difficult to compare dates across different devices, or on a server.

It would be very useful to add a setting that sets each day's date relative to UTC instead. (This can be achieved by adding the line:
```objective-c
// setDisplayedMonth:
[df setTimeZone:[NSTimeZone timeZoneWithName:@"UTC"]];
```
After line 324 in THDatePickerViewController.m.)

**Comment by hons82** [comment]
In version 1.2.0 I'll put the possibility to set the TimeZone different from the default
