### ISSUE TITLE
duplicate symbol _KNSemiModalTransitionStyle in:

### ISSUE THREAD

**Issue by johnny51925** [hons82/THCalendarDatePicker#33]
Wt's going if I import the .h file

#import <THDatePickerViewController.h>

It will build fail 
duplicate symbol _KNSemiModalTransitionStyle in:

Why duplicate symbol?

**Comment by hons82** [comment]
That’s coming from the KNSemiModalView.
Did you import that twice?

Try to search for “KNSemiModalTransitionStyle” in your project. Maybe you’ll find that twice.
And check your build settings. Maybe you import that header twice.

Its hard to guess whats wrong in your project with that tiny bit of information

~Hons

**Comment by montegoulding** [comment]
I bumped into the same issue. The problem is in KNSemiModalViewController:

````
NS_ENUM(NSUInteger, KNSemiModalTransitionStyle) {
	KNSemiModalTransitionStyleSlideUp,
	KNSemiModalTransitionStyleFadeInOut,
	KNSemiModalTransitionStyleFadeIn,
	KNSemiModalTransitionStyleFadeOut,
};
````

should be

````
typedef NS_ENUM(NSUInteger, KNSemiModalTransitionStyle) {
	KNSemiModalTransitionStyleSlideUp,
	KNSemiModalTransitionStyleFadeInOut,
	KNSemiModalTransitionStyleFadeIn,
	KNSemiModalTransitionStyleFadeOut,
};
````

There is already an open PR on this https://github.com/kentnguyen/KNSemiModalViewController/pull/71 but KNSemiModalViewController appears to be unmaintained as the last commit was well over a year ago...

**Comment by hons82** [comment]
Hmmm... 
So there are basically two options
1) we try to contact the developer to ask for an admin account on the repo
2) I copy the repo and publish it under a new name

~hons

**Comment by andres-ciano** [comment]
Cool @hons82 !
I'll move on to your repo as well :D 
Thanks!
