### ISSUE TITLE
Is there a possibility to change the shape of the selected date from square to circle?

### ISSUE THREAD

**Issue by jorielfronda** [hons82/THCalendarDatePicker#37]

**Comment by hons82** [comment]
Currently there is no such option as I use just the background color
```Objective-C
-(void)setSelected:(BOOL)selected{
    if(selected) {
        [self setBackgroundColor:self.selectedBackgroundColor];
        [self.dateButton setSelected:YES];
        [self.dateButton setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
    }
    else {
        [self setBackgroundColor:[UIColor whiteColor]];
        [self.dateButton setSelected:NO];
        [self.dateButton setTitleColor:[UIColor colorWithWhite:.3 alpha:1] forState:UIControlStateNormal];
    }
    [self setCurrentColors];
}
```
Would you be looking for something like [that](https://wmfexcel.files.wordpress.com/2013/11/excel-tips-14-drop-down-calendar.png) or just some android style thing like [that](http://designshack.net/images/designs/date-picker-ui.jpg)

**Comment by jorielfronda** [comment]
I'm looking for a calendar same as this 
![screen shot 2015-09-03 at 8 48 26 pm](https://cloud.githubusercontent.com/assets/13978397/9658594/38fb0b1e-527d-11e5-83d8-9e5e7ca3385c.png)
from: 
https://github.com/mmick66/KDCalendarView

I was not able to run the project, it gives me an error. Currently I'm working on Swift.

**Comment by hons82** [comment]
Take a look at the Swift Example, as it almost does what you're looking for.
The circle is not yet centred, so I'm not yet pushing a new version onto Cocoapods... but it's a beginning :-D

**Comment by hons82** [comment]
Try the v1.2.3. The Swift Sample is setup with rounded buttons
