### ISSUE TITLE
Any chance of adding an option for multiple day selection?

### ISSUE THREAD

**Issue by pascualin** [hons82/THCalendarDatePicker#39]
I have a requirement on my project to select multiple days, do you think this could be useful for other users too? I will most likely modify the component to adapt to my needs, so I was wondering if this would be a pull request you would accept.

Thanks
![screen shot 2015-09-04 at 16 42 23](https://cloud.githubusercontent.com/assets/330084/9679754/f29f2ac2-5323-11e5-8697-2cbf71186661.png)

**Comment by hons82** [comment]
This might be interesting…
I’d accept a pull for this, as long as the default remains single selection and it can be switched on in case it is needed.

thx a lot
~Hannes
