### ISSUE TITLE
Weeks start with Sunday

### ISSUE THREAD

**Issue by niveus** [hons82/THCalendarDatePicker#4]
It would be nice to be able to make the calendar appear beginning with Sunday instead of Monday

**Comment by palmitoto** [comment]
Hi, i open again this thread cause i'm using french locale and the calendar begin the sunday instead of monday. I'm using THCalendarDatePicker 1.2 (pod), any idea ?

Sincerely,

**Comment by uzman** [comment]
i set locale to Italy.
but it starts with Sunday. (iOS 10)
any help?

**Comment by hons82** [comment]
I haven't seen this, cause it was never re-opened.
I'll check soon

**Comment by Oggerschummer** [comment]
@hons82 ,
I had the same issue. Reason is that whenever you initialize the NSCalender it´s not getting supplied with the current locale.
Putting in something like 
`NSCalendar* cal =[NSCalendar calendarWithIdentifier:NSCalendarIdentifierGregorian];
[cal setLocale:[NSLocale currentLocale]];`
should do the trick. At least it helped in my case.

May you could update the code.
