### ISSUE TITLE
Slow animation

### ISSUE THREAD

**Issue by shoaib-akhtar** [hons82/THCalendarDatePicker#42]
When i run following code on a button press calendar takes 4 to 5 second to show up. How can we speed it up?

 if(!self.datePicker)
    self.datePicker = [THDatePickerViewController datePicker];
    self.datePicker.date = deadlineDate;
    self.datePicker.delegate = self;
    [self.datePicker setAllowClearDate:NO];
    [self.datePicker setClearAsToday:YES];
    [self.datePicker setAutoCloseOnSelectDate:NO];
    [self.datePicker setAllowSelectionOfSelectedDate:YES];
    [self.datePicker setDisableYearSwitch:YES];
    //[self.datePicker setDisableFutureSelection:NO];
    //[self.datePicker setDaysInHistorySelection:1];
    [self.datePicker setDisableFutureSelection:NO];
    //[self.datePicker setDateTimeZoneWithName:@"UTC"];
    //[self.datePicker setAutoCloseCancelDelay:5.0];
    [self.datePicker setSelectedBackgroundColor:[UIColor colorWithRed:125/255.0 green:208/255.0 blue:0/255.0 alpha:1.0]];
    [self.datePicker setCurrentDateColor:[UIColor colorWithRed:242/255.0 green:121/255.0 blue:53/255.0 alpha:1.0]];
    [self.datePicker setCurrentDateColorSelected:[UIColor yellowColor]];
    
    [self.datePicker setDateHasItemsCallback:^BOOL(NSDate *date) {
        int tmp = (arc4random() % 30)+1;
        return (tmp % 5 == 0);
    }];
    //[self.datePicker slideUpInView:self.view withModalColor:[UIColor lightGrayColor]];
    [[[SessionController getSharedInstance] getViewController] presentSemiViewController:self.datePicker withOptions:@{
                                                                                                                       KNSemiModalOptionKeys.pushParentBack    : @(NO),
                                                                                                                       KNSemiModalOptionKeys.animationDuration : @(0.3),
                                                                                                                       KNSemiModalOptionKeys.shadowOpacity     : @(0.3),
                                                                                                                       }];

**Comment by hons82** [comment]
That's more or less the code from the sample I guess... Never seen such a behavior... For me it's like half a second to finish the animation. Actually version 1.2.2 contains a property to set the animation speed.

On which device r u testing? Wait... R u using the simulator? There is a setting in the simulator called "toggle slow animations" which is used to debug animations. I guess u have that one switched on

**Comment by shoaib-akhtar** [comment]
It is happening on iPad2 iOS 8.3. I will let know if i find any solution. Thanks

**Comment by hons82** [comment]
I,ve the same device here but with 8.4.
0.5 seconds at most. Using the sample app...

I've no idea how to solve that remotely...
