### ISSUE TITLE
Multiple date picker and Start date, End date feature

### ISSUE THREAD

**Issue by manhcuong27** [hons82/THCalendarDatePicker#43]
Hello,

I'm using your date picker, it works great. But do you have a way to implement multiple date pickers with Start Date and End Date feature, the picker for start date and end date should be limited by each others

Thanks.

**Comment by manhcuong27** [comment]
Anyone can help me with this ? Thanks

**Comment by hons82** [comment]
I'm not really sure what u need there

**Comment by manhcuong27** [comment]
For example, I have 2 UITextField that implement THCalendarDatePicker, one is the Start date, one is the End date. If you choose a date for Start date, then the minimum date for End date is the date from Start date field. And if you choose a date for End date, then the maximum date for Start date is the date from End date field.

**Comment by manhcuong27** [comment]
Hello @hons82 , can you please help me ? Thanks.

**Comment by hons82** [comment]
Currently what you can do is to take the callback and set the date of the second textfield accordingly.
But there is (currently) no possibility to set an end/start date for the selection meaning, that if your user sets the start date to tomorrow you can set the end date to the day after tomorrow using the callback.
If he enters then a end date that is yesterday, that can’t be blocked. What you can do in this case is to set the start date to the day before yesterday using the callback again.

~hons

**Comment by subhash08** [comment]
Hello @hons82 , can you please try to fix it,  want to add two datePicker with textfields for my project.

**Comment by subhash08** [comment]
@manhcuong27  can you please help ??

**Comment by hons82** [comment]
Okay, I'll rewrite my answer and try to explain what I meant:
What you want to achieve is in fact already implemented, maybe not in the way that you expect it, but its there.

1) Create two Textfields, buttons whatever you like
2) in the on click method you define the Calendar component who u like it to be and set those two variables accordingly
```Objective-C
    NSUInteger _daysInHistory;
    NSUInteger _daysInFuture;
```
With those you can limit the number of days selectable in the direction future or history

All that you'd need to do is change this in line 570
```Objective-C
NSDate *currentDate = [[NSDate date] dateWithOutTime];
```
to 
```Objective-C
NSDate *currentDate = [[self internalDate] dateWithOutTime];
```
This should be done with a configurable switch when it should be in the final product.
There could even be a method that takes two dates and sets the history/future integers accordingly.

If you find a nice solution drop me a PR and I integrate it.

~hons82

**Comment by hons82** [comment]
In this commit you'll almost find the right solution.
Unfortunately I need to go now, so I'll continue maybe next week on this
cheers

**Comment by hons82** [comment]
So, Example done! Build is sent to Cocoapods as v1.2.4

Have fun
