### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by ivangodfather** [hons82/THCalendarDatePicker#47]
Hi, i've got warnings in the pod, how can i ignore them or can you fix them?
<img width="953" alt="screen shot 2015-09-17 at 23 46 52" src="https://cloud.githubusercontent.com/assets/1838117/9946870/726c2e4a-5d96-11e5-90cc-c0ced019cc6a.png">

**Comment by hons82** [comment]
Actually you can ignore them for now...
Its just deprecated warnings...

I'm going to fix them soon, or you can fix them and send me a pull request if you like
