### ISSUE TITLE
Ambiguous reference to member 'KNSemiModalOptionKeys'

### ISSUE THREAD

**Issue by katoree** [hons82/THCalendarDatePicker#49]
```
presentSemiViewController(datePicker, withOptions: [
            KNSemiModalOptionKeys.pushParentBack    : NSNumber(bool: false),
            KNSemiModalOptionKeys.animationDuration : NSNumber(float: 1.0),
            KNSemiModalOptionKeys.shadowOpacity     : NSNumber(float: 0.3)
            ])
```

The first line brings about the error

**Comment by hons82** [comment]
Try it like I did in the Sample. That should work. 
Or is it Swift? There is a Problem. If u know how to solve it send me a PR

**Comment by katoree** [comment]
It is Swift 2.0.

I ended up adjusting and commenting it out as seen below just so we can get rid of the error and build but its not a real fix.

```
presentSemiViewController(datePicker, withOptions:nil/* [
            KNSemiModalOptionKeys.shadowOpacity     : 0.3 as Float,
            KNSemiModalOptionKeys.animationDuration : 1.0 as Float,
            KNSemiModalOptionKeys.pushParentBack    : false as Bool
            ]*/)
```

**Comment by hons82** [comment]
The is a problem inthis Knsemimodal component that i'm using there...
When I arrive to the office today I'll work on a fix

**Comment by hons82** [comment]
I've added it to the latest Swift Sample... but I'm not really happy with it..
