### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by diogo10** [hons82/THCalendarDatePicker#50]
<img width="1010" alt="screen shot 2015-10-11 at 3 35 55 p m" src="https://cloud.githubusercontent.com/assets/1541244/10417279/cda8a15e-702d-11e5-9749-10fc63bce8f5.png">

**Comment by diogo10** [comment]
when I write 

presentSemiViewController(datePicker)


works fine....

**Comment by hons82** [comment]
Yes, I know... It is because of the options...
Just have a look at #49 there it's explained, and in the latest commit there is a sample dealing with that
