### ISSUE TITLE
Title for calendar picker

### ISSUE THREAD

**Issue by jeremiescheer** [hons82/THCalendarDatePicker#51]
The calendar picker is great, but I think that something is missing : it could be interesting to have the possibility to add a title to the calendar, to know what we are selecting date for.

**Comment by hons82** [comment]
Could you add a screenshot of that?
I'm not sure what this means

**Comment by jeremiescheer** [comment]
Here is a screenshot of another picker that have title on the backdrop view : as you can see it, there is the title "Heure de l'acte".
![pickertitle](https://cloud.githubusercontent.com/assets/12546283/10487863/5d0a1638-7296-11e5-88ce-aba09b6180cf.png)

**Comment by hons82** [comment]
I've merged your PR... still need to do some tests before pushing it to the cocoapods repo
