### ISSUE TITLE
problem with KNSemiModalOption

### ISSUE THREAD

**Issue by JonathanLu2393** [hons82/THCalendarDatePicker#54]
<img width="1123" alt="screen shot 2015-10-19 at 11 39 48 am" src="https://cloud.githubusercontent.com/assets/14320528/10587500/25fdbf0a-7656-11e5-9f0c-06c7b7fabd77.png">

Is there a way to solve this?

**Comment by hons82** [comment]
Pleas have a look at #49 and #50.
Those might help

**Comment by JonathanLu2393** [comment]
Thanks. Sorry for not looking before.

**Comment by hons82** [comment]
Got it again now. Maybe its not workin anymore
