### ISSUE TITLE
How To add Date

### ISSUE THREAD

**Issue by agomaa** [hons82/THCalendarDatePicker#56]
Thanks for this pretty Control i appreciate your efforts
can you advice if i have dates like 
"2015-09-10",
        "2015-09-12",
        "2015-09-13"
and need to use 
[self.datePicker setDateHasItemsCallback:^BOOL(NSDate *date
how to do
Regards

**Comment by hons82** [comment]
In the sample you have this portion of code
```Objective-C
[self.datePicker setDateHasItemsCallback:^BOOL(NSDate *date) {
        int tmp = (arc4random() % 30)+1;
        return (tmp % 5 == 0);
    }];
```
This is called for every shown date. In the sample it is showing the little dot randomly, but you can check in this block if the ```date``` is in an array of dates like yours and return true if it is and false otherwise
