### ISSUE TITLE
__NSCFCalendar components:fromDate

### ISSUE THREAD

**Issue by johnny51925** [hons82/THCalendarDatePicker#60]
What is going on after I updated to 1.2.5?

*** -[__NSCFCalendar components:fromDate:]: date cannot be nil
Future exception.

Thank You

**Comment by hons82** [comment]
Haven't seen this until now...

**Comment by edekhayser** [comment]
@johnny51925  Have you found a solution to this?

**Comment by hons82** [comment]
I didn't got any more info from that user, so I couldn't investigate on it.
What are you doing to get that error?

**Comment by edekhayser** [comment]
@hons82 The backtrace points to [THDatePickerViewController dateDayTapped:]. Based on some debugging, I determined that this is the problematic line:

        [self.currentDay setLightText:![self dateInCurrentMonth:self.currentDay.date]];

self.currentDay is nil for some reason, which is causing this problem.

I've been trying to find out why this is, but I don't know the project as well as you do. Would you be able to look into this? Thanks!

**Comment by edekhayser** [comment]
More info – here is my setup for the picker:

```
let vc = THDatePickerViewController.datePicker()
vc.setAllowClearDate(false)
vc.setClearAsToday(false)
vc.setAutoCloseOnSelectDate(true)
vc.setAllowSelectionOfSelectedDate(false)
vc.setDisableHistorySelection(true)
vc.setDisableFutureSelection(false)
vc.setDisableYearSwitch(true)
vc.delegate = self
presentSemiViewController(vc, withOptions: [
	KNSemiModalOptionKeys.pushParentBack.takeRetainedValue()    : NSNumber(bool: false),
	KNSemiModalOptionKeys.animationDuration.takeRetainedValue() : NSNumber(float: 0.3),
	KNSemiModalOptionKeys.shadowOpacity.takeRetainedValue()     : NSNumber(float: 0)
])
```

**Comment by Jiar** [comment]
I meet the same problem. The solution is as follows：
`self.datePicker = [THDatePickerViewController datePicker];
self.datePicker.delegate = self;
// this is the way to solution the problem
self.datePicker.date = [NSDate date];
[self.datePicker setAllowClearDate:NO];
[self.datePicker setClearAsToday:YES];
[self.datePicker setAutoCloseOnSelectDate:NO];
[self.datePicker setDisableHistorySelection:YES];
[self.datePicker setAllowSelectionOfSelectedDate:YES];
[self.datePicker setDisableYearSwitch:NO];
[self.datePicker setSelectedBackgroundColor:[UIColor colorWithRed:125/255.0 green:208/255.0 blue:0/255.0 alpha:1.0]];
[self.datePicker setCurrentDateColor:[UIColor colorWithRed:242/255.0 green:121/255.0 blue:53/255.0 alpha:1.0]];
[self.datePicker setCurrentDateColorSelected:[UIColor yellowColor]];
[self.datePicker setDateHasItemsCallback:^BOOL(NSDate *date) {
    return NO;
}];
[self presentSemiViewController:self.datePicker withOptions:@{
                                                              KNSemiModalOptionKeys.pushParentBack    : @(NO),
                                                              KNSemiModalOptionKeys.animationDuration : @(0.6),
                                                              KNSemiModalOptionKeys.shadowOpacity     : @(0.3),
                                                              }];`
