### ISSUE TITLE
cannot convert value of type 'Unmanaged<NSString>!' to expected dictionary key type 'NSObject'

### ISSUE THREAD

**Issue by ppeelen** [hons82/THCalendarDatePicker#63]
Hi!

I am experiencing problems with `KNSemiModalOptionKeys` when trying to present the picker. 
<img width="638" alt="skarmavbild 2015-12-29 kl 14 12 16" src="https://cloud.githubusercontent.com/assets/1107400/12034817/77f6ffca-ae36-11e5-9dab-8d880bf0d5b6.png">

I am using the example code supplied in the Readme.

Any suggestion on how to solve this? Anything I am doing wrong?

Cheers,
Paul

**Comment by hons82** [comment]
Ops, you"re right...
I need to update the README... actually you can find a working example in the [Swift Example project](https://github.com/hons82/THCalendarDatePicker/blob/master/THCalendarDatePickerFromToSwiftExample/THCalendarDatePickerFromToSwiftExample/ViewController.swift)

**Comment by ppeelen** [comment]
Perfect. Thanks.

**Comment by ngothanhtai** [comment]
Hi,
You should update README.md example code for Swift. I have to look around and search to solve this problem. Thanks!

**Comment by hons82** [comment]
With the next update probably...
Or change it and send me a PR

best
hons

**Comment by ispiropoulos** [comment]
An extension can help you use this amongst multiple view controllers, there you go:

`extension Unmanaged {
    func convertCfTypeToString() -> String?{
        let value = Unmanaged<CFStringRef>.fromOpaque(
            self.toOpaque()).takeUnretainedValue() as CFStringRef
        if CFGetTypeID(value) == CFStringGetTypeID(){
            return value as String
        } else {
            return nil
        }
    }
}
`
