### ISSUE TITLE
[__NSDate dateWithOutTime]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by ghost** [hons82/THCalendarDatePicker#64]
self.datepicker.date = [NSDate date];

Any idea why this happened?

**Comment by hons82** [comment]
Have u tried to run the THCalendarDatePickerExample?
There I'm setting it up like this...
But I guess you did some partial manual import of the project files and omitted to add the NSDate+Difference[.h | .m] classes either in the copying or in the linking... right?

**Comment by EmanKassem** [comment]
THCalendarDatePickerExample have issue in Pods it is red coloured.
I could not run it.

I used cocoa pods to use THCalendarDatePickerExample, I did not unlock pod or edit anything.

**Comment by hons82** [comment]
Did u get something like that when u update the pod?
```bash
THCalendarDatePickerExample$ pod update
Update all pods
Updating local specs repositories

CocoaPods 1.0.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `THCalendarDatePicker` from `./../../THCalendarDatePicker`
Downloading dependencies
Using KNSemiModalViewController_hons82 (0.4.4)
Using THCalendarDatePicker (1.2.5)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total
pods installed.
```

**Comment by EmanKassem** [comment]
![thcalendardatepickerexampleissue](https://cloud.githubusercontent.com/assets/16559076/12116768/da575bae-b3c4-11e5-98e9-c0ebd74e7fc9.png)
Here is Pod issue picture.

**Comment by EmanKassem** [comment]
Actually I don't remember.

Do you suggest to uninstall pod then install it again?

**Comment by hons82** [comment]
What u can try is to delete the ```Podfile.lock``` 
Then re-run ```pod update```
And then ```open THCalendarDatePickerExample.xcworkspace/``` 
All of those in a console

**Comment by EmanKassem** [comment]
This is what I got now.

=================
Update all pods
Updating local specs repositories

CocoaPods 1.0.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using KNSemiModalViewController_hons82 (0.4.4)
Using THCalendarDatePicker (1.2.5)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total
pods installed.

[!] The `Tawasol Pro [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-Tawasol Pro/Pods-Tawasol Pro.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Tawasol Pro [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-Tawasol Pro/Pods-Tawasol Pro.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
