### ISSUE TITLE
Flickering on orientation change, disable landscape support

### ISSUE THREAD

**Issue by yakubbaev** [hons82/THCalendarDatePicker#68]

**Comment by hons82** [comment]
Is that a question?
If u want me to check something I'll need a bit more info.
Did u run the sample? 
On a Device or the simulator?
Which Version?
...

**Comment by yakubbaev** [comment]
Sorry for bad explanation. 
My project is strickted to portrait only, and if I rotate phone when date picker is present, there's some flickering. I've solved this by replacing your implementation of `KNSemiModalViewController_hons82` with pure `KNSemiModalViewController`.

**Comment by decaluwepatrick** [comment]
I have the same problem. Where did you replace this?

**Comment by yakubbaev** [comment]
I've replaced line in ```THCalendarDatePicker.podspec``` to look like 

    s.dependency 			'KNSemiModalViewController'
 and referenced it in my ```Podfile``` as ```pod 'THCalendarDatePicker', :path => 'HackedPods/THCalendarDatePicker'```

**Comment by decaluwepatrick** [comment]
Thank you for your quick answer! I am not very familiar with pods yet and I don't seem to find a file named THCalendarDatePicker.podspec. It is not in the "THCalendarDatePicker" folder in the pods directory. Did you make this file?

**Comment by hons82** [comment]
The podspec is located at the root of the repository

**Comment by rajeev2iOS** [comment]
i cant find THCalendarDatePicker.podspec in my workspace

**Comment by hons82** [comment]
https://github.com/hons82/THCalendarDatePicker/blob/master/THCalendarDatePicker.podspec

**Comment by rajeev2iOS** [comment]
this is okay, but THCalendarDatePicker installed via pods, i can not find the lcoation of pod spec

**Comment by hons82** [comment]
Did you ever install a pod?
Podspec --> used to define
Pofile --> when u use a Library

Please, check the samples
