### ISSUE TITLE
multiple selection

### ISSUE THREAD

**Issue by mahmoudashraf93** [hons82/THCalendarDatePicker#69]
cant select multiple days is there any solution?

**Comment by pascualin** [comment]
I have an implementation for the multiple days selection, if this is something of interest for people I can do a pull request

**Comment by hons82** [comment]
Hi,
Nice Idea. Currently I,ve no implementation for multiple selection. If you have one that is configurable and off by default....
Then I'd like to add it

**Comment by pascualin** [comment]
I have created a pull request with my implementation, there are some conflicts to be merged but they look pretty straight forward.

**Comment by rupeshsaxena** [comment]
Does it have onDrag multi-selection?

**Comment by hons82** [comment]
I've just commited the changes you made from #70
