### ISSUE TITLE
Disable multiple selection for dates

### ISSUE THREAD

**Issue by varuna82** [hons82/THCalendarDatePicker#71]
I am using the calendar control to select a date. However disabling multiple date selection does not seem to disable selection of multiple dates.

Here's the code I've used to disable multi-day selection.
`
dp.setAllowMultiDaySelection(false)  // <--- disable multi-day selection
`

**Comment by hons82** [comment]
THX...
I had to change to much after taking that #69 ... Just made a push, hopefully its working again
