### ISSUE TITLE
Select all dates between Max and Min selected dates

### ISSUE THREAD

**Issue by rajeev2iOS** [hons82/THCalendarDatePicker#72]
I am using THCalendarDatePicker in my project, it's really good to represent calendar appearance. Is there any way to select all dates between Maximum and Minimum dates selected by user while multipleselction is enabled?

**Comment by hons82** [comment]
Currently there is no such solution

But it should be quite simple to have a method with Select fromDate ToDate and set the selected accordingly at initial launch

**Comment by rajeev2iOS** [comment]
thanks @hons82  but before that i mess up with small issue. THCalendarDatePicker reintializing on top of it again with orientation change. I've enabled only portrait in my app

**Comment by hons82** [comment]
I just merged a branch that allows that.
But it is completely unchecked by me, so test it well
