### ISSUE TITLE
setDaysInHistorySelection: and setDaysInFutureSelection: don't actually disable selection

### ISSUE THREAD

**Issue by vkaramov** [hons82/THCalendarDatePicker#74]
setDaysInHistorySelection: and setDaysInFutureSelection: don't actually disable selection in the past and in the future respectively. Their behaviour also depends on setDate: call. In current implementation setDate: should be called **after** these methods.

**Comment by hons82** [comment]
setDaysIn...: Actually they do work... just set the number of days that you'll allow to go to past/future 
0 = disabled = allow every day in past/future
1 = 0 days = not allow to go to past/future
x = x-1 days are allowed

setDate: You **can** call it after, but in that case you override the settings that you made earlier, sou you **should** not. Actually it is supposed to be called first and then if you wanna override manually these settings so you should and can do so.

I've checked your PR #75 too... I'll answer there

**Comment by vkaramov** [comment]
In the sample app, change 
```
    [self.datePicker setDaysInHistorySelection:1];
    [self.datePicker setDaysInFutureSelection:0];
```
to

```
    [self.datePicker setDaysInHistorySelection:45];
    [self.datePicker setDaysInFutureSelection:0];
```

and run the sample. The expected result is:
1) You can select up to 45 days in the past
2) You can't select dates in future.

Actual result:
1) You can't select dates in the past
2) You can select ANY dates in the future.

Proof
[http://i.piccy.info/i9/21e32831fdc609d3f19554e3967cc7fb/1459450653/70719/1010450/Simulator_Screen_Shot_31_marta_2016_g_21_56_53.png](url)

**Comment by hons82** [comment]
If I run it: The expected result is:
1) You can select up to 44 days in the past
2) **You can select any date in future.**

Actual result:
1) You can select up to 44 days in the past
2) You can select any date in future.
