### ISSUE TITLE
choose range date, start date to end date

### ISSUE THREAD

**Issue by chinhndse03483** [hons82/THCalendarDatePicker#79]
can you create function to choose range date ?, example, in my project, I choose start date and end date to get data in rang date. 
Can you help me?

**Comment by hons82** [comment]
You need the selectable date to be between two dates?

**Comment by chinhndse03483** [comment]
no, I want to select date start and date end.

**Comment by hons82** [comment]
Of what? Of the selectable Dates? or the selected dates?

**Comment by chinhndse03483** [comment]
selected dates

**Comment by hons82** [comment]
I just merged a PR that should enable that.
Due to lack of time I did not check it yet
