### ISSUE TITLE
[<THDatePickerViewController 0x177911e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key titleLabel.'

### ISSUE THREAD

**Issue by palmitoto** [hons82/THCalendarDatePicker#82]
On v 1.2.8 when i call presentSemiViewController, i obtain this error: 

[<THDatePickerViewController 0x177911e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key titleLabel.'

Any ideas ?

**Comment by hons82** [comment]
I'm not working for the company that I made this component for anymore, so I'm not actively developing on this right now.

Basically my suggestion is always to download the whole repo... maybe not the trunk, but at the tag of the vesion ur intrested in and try the sample projects. If they don't work open an issue, if they do... yeah then its ur fault :-)

**Comment by palmitoto** [comment]
This module works until v2.1.2, after that version it didn't. I'm using code given on example.

**Comment by hons82** [comment]
So it is omething wrong with [this](https://github.com/hons82/THCalendarDatePicker/commit/57b496f019bd5d3faaefdab8a2b37e44ec215ca9) commit.

On my machine the samples are all working on the latest trunk...
As said, I'm not actively developing on this anymore. You can put a little more of the error message in here, at least showing a linenumber and how u call it or fix it and send a PR
