### ISSUE TITLE
Future Exception - "Date cannot be nil" on Date Selection

### ISSUE THREAD

**Issue by cwalmsley** [hons82/THCalendarDatePicker#83]
I have implemented the library using Swift 2.3 and see the below notification in the console when selecting a date from the picker.

Its a vanilla implementation of the library - with no selected dates initialized. I have disabled multi date selection. 

The selected date looks good to me in the delegate method and I can successfully parse to my desired format, so I find this warning is confusing.

2016-10-26 22:33:18.804 MyApp[20469:257834] **\* -[**NSCFCalendar components:fromDate:]: date cannot be nil
Future exception.
A few of these errors are going to be reported with this complaint, then further violations will simply be ignored.
Here is the backtrace where this occurred this time (some frames may be missing due to compiler optimizations):
(
    0   CoreFoundation                      0x0000000106a418f2 -[__NSCFCalendar components:fromDate:] + 130
    1   CoreFoundation                      0x0000000106a417fe -[_NSCopyOnWriteCalendarWrapper components:fromDate:] + 78
    2   THCalendarDatePicker                0x000000010471e37f -[THDatePickerViewController dateInCurrentMonth:] + 207
    3   THCalendarDatePicker                0x000000010471b977 -[THDatePickerViewController dateDayTapped:] + 567
    4   THCalendarDatePicker                0x0000000104715f29 -[THDateDay dateButtonTapped:] + 89
    5   UIKit                               0x0000000104772b88 -[UIApplication sendAction:to:from:forEvent:] + 83
    6   UIKit                               0x00000001048f82b2 -[UIControl sendAction:to:forEvent:] + 67
    7   UIKit                               0x00000001048f85cb -[UIControl _sendActionsForEvents:withEvent:] + 444
    8   UIKit                               0x00000001048f74c7 -[UIControl touchesEnded:withEvent:] + 668
    9   UIKit                               0x00000001047e00d5 -[UIWindow _sendTouchesForEvent:] + 2747
    10  UIKit                               0x00000001047e17c3 -[UIWindow sendEvent:] + 4011
    11  UIKit                               0x000000010478ea33 -[UIApplication sendEvent:] + 371
    12  UIKit                               0x0000000104f80b6d __dispatchPreprocessedEventFromEventQueue + 3248
    13  UIKit                               0x0000000104f79817 __handleEventQueue + 4879
    14  CoreFoundation                      0x0000000106a0b311 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
    15  CoreFoundation                      0x00000001069f059c __CFRunLoopDoSources0 + 556
    16  CoreFoundation                      0x00000001069efa86 __CFRunLoopRun + 918
    17  CoreFoundation                      0x00000001069ef494 CFRunLoopRunSpecific + 420
    18  GraphicsServices                    0x0000000109288a6f GSEventRunModal + 161
    19  UIKit                               0x0000000104770f34 UIApplicationMain + 159
    20  MyApp                        0x00000001008a99a2 main + 114
    21  libdyld.dylib                       0x0000000107a4e68d start + 1
    22  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by hons82** [comment]
Unfortunately I was never able to reproduce that...
I tend to close this issue...
