### ISSUE TITLE
Strange Object to BOOL conversion

### ISSUE THREAD

**Issue by truebucha** [hons82/THCalendarDatePicker#92]
in THDatePickerViewController at line 455
`- (void)setInternalDate:(NSDate *)internalDate{
...
self.clearBtn.enabled = internalDate; // pointer to bool conversion
...
`

**Comment by hons82** [comment]
This is not so obvious, but it is a short form of object != nil.
If you like you can send me a PR to make it more obvious

**Comment by truebucha** [comment]
it is obvious not object != nil. it is assignment object address (pointer integer) to bool(typedef of integer), so it works because pointer integer not equal 0. but xcode shows warning and I agree with it. there are possible issues in swift. never mind.

**Comment by hons82** [comment]
You're right. I didn't really think about it.
Actually I'm not using/maintaining this control anymore...
